### ISSUE TITLE
Lightning Talk: The smaller the better?: Micro-Frontends

### ISSUE THREAD

**Issue by itsyme** [nus-cs3281/2024#64]

**Comment by damithc** [comment]
@itsyme is this meant to be round C? 
Round C is meant to be a repeat of A or B (or A+B), not a new talk.

**Comment by itsyme** [comment]
Yep! Is it alright if my talk contains some links to both talk A and B rather than a repeat/combination of both? @damithc

**Comment by damithc** [comment]
@itsyme It needs to be the same topic. I need to see how much you improved in the second try. Also, there'll be differences (and additional requirements) for round C -- so, it's not exactly repeating the same talk. More details soon.
